FROM nginx:1.20
MAINTAINER shijieming
ENV TZ Asia/Shanghai
RUN rm -rf /usr/share/nginx/html
COPY ./ruoyi-ui/dist /usr/share/nginx/html
COPY ./docker/nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/share/nginx/html
